catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.7
  vite-plus: 0.2.7
  satteri: 0.9.5
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
packages:
  - "packages/*"
  - "examples/*"
